name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v22.16.0
      uses: actions/setup-node@v4
      with:
        node-version: v22.16.0
    - name: Install dependencies
      run: npm install
    - name: Run integration tests
      run: npm test

  security_tests:
    needs:  unit_tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v22.16.0
      uses: actions/setup-node@v4
      with:
        node-version: v22.16.0
    - name: Install dependencies
      run: npm install
    - name: Run integration tests
      run: npm test
    - name: Run security tests
      run: npm audit